name: Practice Deployment
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: |
          cd exercise/
          npm ci
      - name: Check the Lint
        run: |
          cd exercise/
          npm run lint
      - name: Check the test
        run: |
          cd exercise/
          npm run test
      - name: Build the project
        run: |
          cd exercise/
          npm run build
      - name: Deploy the project
        run: echo "Deployed...."
