name: test Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: current working dir
        run: |
          pwd
          ls -l
      - name: Install dependencies
        run: |
          cd frontend/
          npm ci
      - name: Run Tests
        run: |
          cd frontend/
          npm test
  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: |
          cd frontend/
          npm ci
      - name: Build the Project
        run: |
          cd frontend/
          npm run build
          ls -l
      - name: Deploy
        run: echo "Deploying..."
